In [32]:
import pandas as pd

In [33]:
file_path="C:/dev/project/SKN27-FINAL-4Team/etl/datasets/personality_training/embedding_source/mbtibench_raw_source_records.csv"

In [34]:
from langchain_community.document_loaders import CSVLoader

# CSV 파일을 LangChain Document 형태로 불러오기 위한 CSVLoader 설정
loader = CSVLoader(
    file_path=file_path,          # 불러올 CSV 파일 경로 (변수 file_path)
    encoding='utf-8',             # CSV 파일 인코딩 방식

    # CSV 파싱 설정
    csv_args={
        'delimiter': ',',         # CSV의 열 구분자 (기본 콤마)
    }
)

In [35]:
docs1 = loader.load() 

print(f"로드된 문서의 수: {len(docs1)}")

로드된 문서의 수: 286

In [36]:
for i, doc in enumerate(docs1[:5]):
    print("="*50)
    print(f"Document {i+1}:")
    print(f"   - 타입: {type(doc)}")
    print(f"   - page_content 타입: {type(doc.page_content)}")
    print(f"   - metadata 타입: {type(doc.metadata)}")
    print(f"   - metadata 내용: {doc.metadata}")
    print(f"   - 내용 길이: {len(doc.page_content)} 문자")
    print(f"   - 내용: \n{doc.page_content}")
    print()

==================================================
Document 1:
   - 타입: <class 'langchain_core.documents.base.Document'>
   - page_content 타입: <class 'str'>
   - metadata 타입: <class 'dict'>
   - metadata 내용: {'source': 'C:/dev/project/SKN27-FINAL-4Team/etl/datasets/personality_training/embedding_source/mbtibench_raw_source_records.csv', 'row': 0}
   - 내용 길이: 1921 문자
   - 내용:
﻿source_dataset: mbtibench
source_user_id: 1
source_name: kaggle
annotation: {'E/I': {'A1': 'I-', 'A2': 'I-', 'A3': 'I-'}, 'S/N': {'A1': 'S-', 'A2': 'S+', 'A3': 'S-'}, 'T/F': {'A1': 'T-', 'A2': 'T+', 'A3': 'T-'}, 'J/P': {'A1': 'P-', 'A2': 'J-', 'A3': 'J-'}}
mbti_type:
EI: I
NS: S
FT: T
JP: J
soft_EI_original: 0.8067729083665338
soft_NS_original: 0.11072664359861584
soft_FT_original: 0.13307984790874527
soft_JP_original: 0.48282442748091603
raw_posts: ["think that all these situations depend on who they are and how much you have in common. As years go by I find that life's experiences are a good way to let people know you and interact. ", "I took the last coment a little strongly , and I apologize for the level of my response. Since I am not 13 I find your retort, well childish.  Duty means always fulfilling; epinephrine Stuck on you- lionel Ritchie How could she thank you when 's will clearly be the winner. I will fullfill my duty in this battle for 's I work with somone who is incompetant( slow, lazy, and  lacking in brain power). I find myself doing most of his work as well as mine. I am blessed however to get the respect from my bosses I deserve ", "Well since my enneagram is The Loyal Friend I would say that I am that kind of friend. garden I tend to interested in things I like,but I am up to trying new things. As far as fashion I wear what I like not what is deemed acceptable. When I am tired I am less likely to want to do something ", "I would have to say , because I am married to one who makes my life great!:proud: I also go to music as a relief from trouble, but it always helps me. I especially like to listen to K-LOVE in these times. :happy: I would have to say music is and will be a big part of my life. I like most all kinds classical, rock, alternative, reggae, pop, jazz, blues. I have been to many concerts and enjoyed them all. I have "]
raw_post_count: 4
raw_char_count: 1410

==================================================
Document 2:
   - 타입: <class 'langchain_core.documents.base.Document'>
   - page_content 타입: <class 'str'>
   - metadata 타입: <class 'dict'>
   - metadata 내용: {'source': 'C:/dev/project/SKN27-FINAL-4Team/etl/datasets/personality_training/embedding_source/mbtibench_raw_source_records.csv', 'row': 1}
   - 내용 길이: 2220 문자
   - 내용:
﻿source_dataset: mbtibench
source_user_id: 2
source_name: kaggle
annotation: {'E/I': {'A1': 'I-', 'A2': 'I-', 'A3': 'I-'}, 'S/N': {'A1': 'S+', 'A2': 'S+', 'A3': 'S+'}, 'T/F': {'A1': 'T-', 'A2': 'T+', 'A3': 'T+'}, 'J/P': {'A1': 'P-', 'A2': 'J-', 'A3': 'P-'}}
mbti_type:
EI: I
NS: S
FT: T
JP: P
soft_EI_original: 0.8067729083665338
soft_NS_original: 0.04844290657439454
soft_FT_original: 0.06653992395437269
soft_JP_original: 0.6324110671936759
raw_posts: ["although I did get a PS1 and 2 and Box360 along the way, I never did much with them as I preferred the PC games. 1984 - George Orwell Maybe it's a SJ thing?   You just described me, although I don't so  much backtrack in conversation as edit-as-I-go and it probably does  more to confuse than bore my listener.   P.S. I ", "You answered Visual-7 Auditory-4 Kinesthetic-5   Based on this info you are probably a Visual learner. Oh, yes, that would be me. Even on the rare occasion I make the attempt to get something started early, it gets started ", "until--  --oh, snap! Deadline! Panic! :shocked: Perfidious Flummox   ", "there are more, I just can't think of 'em right now. :frustrating: More warm-ish than hot, the saltier the better, more soggy than crispy and never without ketchup. May the 1th!  Was supposed to be late April but I took my time ", ":proud: They were fun when I was a kid ", "nickel, dime, quarter stuff (this was in the 70's) but I quickly grew out of them.  I have far too much of my own junk that I'm getting rid of, I don't need to be ", "Banker/Innovator And they popup off-center, falling half off the page!  ACK!  :shocked: I was watching an old Dr. Who vid and 'Pralix' was the name of one of the characters.  :tongue: I do so love to sleep. During the week, I'll often get a full night, ~8hrs., but sometimes I'll wake up in the middle of the night practically bouncing off the walls after 3 or 4 hours. I don't get ", "While I don't really have a best friend, the closest friend I have would probably be . That description fits him much better than the others. Next time we get together, maybe I can talk him ", "Just joined up and figured I may as well pop in here and say howdy!  :happy:"]
raw_post_count: 9
raw_char_count: 1690

==================================================
Document 3:
   - 타입: <class 'langchain_core.documents.base.Document'>
   - page_content 타입: <class 'str'>
   - metadata 타입: <class 'dict'>
   - metadata 내용: {'source': 'C:/dev/project/SKN27-FINAL-4Team/etl/datasets/personality_training/embedding_source/mbtibench_raw_source_records.csv', 'row': 2}
   - 내용 길이: 3223 문자
   - 내용:
﻿source_dataset: mbtibench
source_user_id: 3
source_name: kaggle
annotation: {'E/I': {'A1': 'I-', 'A2': 'I-', 'A3': 'I-'}, 'S/N': {'A1': 'S+', 'A2': 'N-', 'A3': 'S-'}, 'T/F': {'A1': 'T+', 'A2': 'T+', 'A3': 'T-'}, 'J/P': {'A1': 'J+', 'A2': 'J+', 'A3': 'J+'}}
mbti_type:
EI: I
NS: S
FT: T
JP: J
soft_EI_original: 0.8067729083665338
soft_NS_original: 0.4411764705882353
soft_FT_original: 0.041825095057034245
soft_JP_original: 0.0
raw_posts: ["dramatic, moving ", ".    do; it's the single holiday that about every 7 years comes around on my birthday!  Here's something to bring a little jollity to your day:  A guy asks a lawyer what his fee is. I charge $50 ", "Every year, Joe takes a week during the summer to relax at his friend's cabin in the Maine woods.  One night after he's just arrived, he's sitting in the cabin when he hears a knock at the door.  He ", "It's remarkable how a few minutes (or even a few seconds) of deep steady breathing can bring down a person's blood pressure AND rate of heartbeat.  When more oxygen is drawn into the lungs less ", "This Short Film is a Stunning Preview of Human Space Exploration  One day x96 and it really is only matter of time x96 humans will set foot on the surfaces of other far-flung worlds in our Solar ", "My I-phone 5 no longer downloads the forum.  It does no more than say loading inside of a rectangular bubble which swells and shrinks as if something is working but yields no results.    Looking ", "The Gael - Theme music from The Last of The Mohicans    this spring I built this Scope Closet in the corner of my garage, squeezed in between the overhead door rail and the wall, in a very small spare space, less than 21 x 18 - less because of ", "APRIL 8 1977 TIME MAGAZINE  was a good guy.  A real gentleman. R.I.P. Robin Williams RobynC, By page 94 (where I am right now) we only know that its a system of 6-satellites lined up to spy on Pakistan/India/China with the resolving power to read headlines of a newspaper on the ", "John Grisham's The Broker a book RobynC would enjoy ", "I had almost the same inclination, but because it was such a poor rendition of the I  Robot stories written by Asimov; and that I find ridiculous special effects off putting. How about poignant? (This video epitomizes that feeling )   man who will chair the House Special Select Committee to investigate Benghazi.    walking out on The Firm we haven't sat in a theatre for anything other than some SciFi.  We get all our movies from the public library in DVD form. That way we can end them and just move on ", "I was a Marine and I stick with my assessment.    I don't accept the low class vernacular for a sublime sex act as suitable dialogue in a public place, particularly when it's a given that there are ", "To answer my own question: Yes, the wife and I walked out on the movie The Firm (starring Tom Cruse) in 1993 because of the constant use of the F word in the first fifteen minutes.  Since that ", "The Shipping News:Amazon:Books I think you could go back to photography, perhaps a different style of photography; an expanded version of your former photographer self.   Now you have a computer and probably an iphone or a "]
raw_post_count: 13
raw_char_count: 2691

==================================================
Document 4:
   - 타입: <class 'langchain_core.documents.base.Document'>
   - page_content 타입: <class 'str'>
   - metadata 타입: <class 'dict'>
   - metadata 내용: {'source': 'C:/dev/project/SKN27-FINAL-4Team/etl/datasets/personality_training/embedding_source/mbtibench_raw_source_records.csv', 'row': 3}
   - 내용 길이: 3082 문자
   - 내용:
﻿source_dataset: mbtibench
source_user_id: 4
source_name: kaggle
annotation: {'E/I': {'A1': 'I-', 'A2': 'I+', 'A3': 'I-'}, 'S/N': {'A1': 'S-', 'A2': 'N-', 'A3': 'S-'}, 'T/F': {'A1': 'T+', 'A2': 'T+', 'A3': 'T+'}, 'J/P': {'A1': 'J-', 'A2': 'J-', 'A3': 'J-'}}
mbti_type:
EI: I
NS: S
FT: T
JP: J
soft_EI_original: 0.9402390438247012
soft_NS_original: 0.4204152249134948
soft_FT_original: 0.0
soft_JP_original: 0.2137404580152672
raw_posts: ["are quite good but i don t like what they do with music ", ".it sounds like someone in bend wants to sabotage them    should forgive one's enemies, but not before they are hanged. Make Restitution No ", "when you broke up with a person there must be a pretty good reasons and thinking that you ve overreacted later is just pink glasses 19 out 36 i find it difficult to find friends cause most people describe me like unsociable asshole ", "..which in fact i am if you want call person that have no desire to talk with people i don t like and ", "Allo allo ", ".genious show from end of 80 Cool but like nothing changes in song ", "..same tune all song    Creed IV: Black Flag Harry Dresden, Uthred Of Bebbanburgh, King Arthur, Owen Deathstalker, The Doctor, John Taylor, Shadowthrone ", "Boondoock saints: All saints day Then remember good times even if they were lie. Sometimes truth just isn t good enough You are an Inventor        Your imagination, self-reliance, openness to new things, and appreciation for utility combine to make you an INVENTOR. The old sailors who traveled Earth's seas were said to have loved the  ocean. The great captains said they were married to the sea or called  the sea their mistress. Modern sailors held no such ", "Simple beautiful. It s like beggining of something new ", ".full of hope but also fear. Simply beautiful     AE so you re saying she acts like female? i rather enjoy when people tells me i m scary Personality of suzie shooter, look of molly carpenter and mind of hermione granger Don t like it but i m using it cause there aren t any normal phones to buy I actually more like publishing houses that aren t directly under DC but they are part of it example Vertigo comics. Dc has great stories and great heroes just their problems are multiple series ", "I think charity organisations are fraud for money laundering so i ll never give them anything ", "..and from my experience most people who are beggars are just too lazy and they don t want work only when i m drunk i don t take notes I have no idea how women think i don t care what anyone thinks of me The Dark Eye: Demonicon Imothep what do you consider by romantic period? Alexandar psychology is a fringe science imperator STAR WARS (original trilogy) Alderaan Tsunami Firefly people are cheap assholes it doesn t have anything to do with personality ", "go to them and say them you want money now i don t have internet One should forgive one's enemies, but not before they are hanged. mix between german shepard and illyrian sheepdog capricorn why don t they just shoot Voldemort? star wars"]
raw_post_count: 13
raw_char_count: 2552

==================================================
Document 5:
   - 타입: <class 'langchain_core.documents.base.Document'>
   - page_content 타입: <class 'str'>
   - metadata 타입: <class 'dict'>
   - metadata 내용: {'source': 'C:/dev/project/SKN27-FINAL-4Team/etl/datasets/personality_training/embedding_source/mbtibench_raw_source_records.csv', 'row': 4}
   - 내용 길이: 3304 문자
   - 내용:
﻿source_dataset: mbtibench
source_user_id: 5
source_name: kaggle
annotation: {'E/I': {'A1': 'I-', 'A2': 'I-', 'A3': 'I-'}, 'S/N': {'A1': 'S-', 'A2': 'N+', 'A3': 'S-'}, 'T/F': {'A1': 'F-', 'A2': 'F+', 'A3': 'F-'}, 'J/P': {'A1': 'J+', 'A2': 'J+', 'A3': 'J+'}}
mbti_type:
EI: I
NS: S
FT: F
JP: J
soft_EI_original: 0.8067729083665338
soft_NS_original: 0.45674740484429066
soft_FT_original: 0.9225092250922509
soft_JP_original: 0.0
raw_posts: ["I am a 14 year old boy, and a high school freshman. I have two older brothers, one born in 1992 (10 years older)and the other born in 1995 (7 years older). The oldest one moved out in December and ", "I don't care if it's flirting or bullying, it makes me uncomfortable and pissed off, and I'm straight! I'm a boy, and I just remembered now he's bi :0 But that doesn't mean he can just take my stuff and then touch me. I don't care what your orientation is, don't touch me unless your my friend! Oh, thanks! :) Thanks, but the thing is I don't even have a lot of pencils. Before he came along, I had 6. Now I have 3. Plus, the pencils he took were high quality. Today I tried to trade 2 not as good mechanical ", "So I'm a freshman in high school, and there's this one guy (also freshman) I met on the first day I came (I started school 1 week late, it's a long story). He was in my 6th period English, and this ", "I'm gonna try out for baseball! The only thing is that I'm a boy. I just promoted from 8th grade 3 weeks ago and I'm going to start high school in less than 2 months. Help for anything?  Then he does his annoying sounding laugh. He can't have a disability because ", "It's also weird because all the other TAs in other periods I know. I mean ALL the other TAs. It's not fair. He's not from a foreign country, he speaks perfect English, but then For no apparent reason he just uses some annoying accent. And at our school we've been writing the date like month/day/year for 3 ", "So for my elective I am a TA (Teacher's aide) for the Office and my partner is really annoying me. He talks too much that it gets on my nerves, and whenever he reads any name from the book with ", "I'm nervous, and at the same time I don't even want to do it. Mario Kart DS I forgot to put multiple choice for my pool, and I can't edit it. There should be something for editing poll options. Thank you so much! I am in the advanced math class and it's hard, but I can still keep an A+ in it. Hopefully it will help me in high school. Also, I am a fast runner and I have a good mile time (my ", "Oriental Flavor Top Ramen ", "I'm getting a cold. The Giver by Lois Lowry (in class) Having a combover, and when just going out still looking kind of in nice clothes, and with a kind of serious face, which is kind of me. I might like multiple girls? Help? Btw, I'm only in 8th grade so ", "How can you get your post ranking up? Mario Super Sluggers and I just lost 😡 I keep saying that I'll do my homework at this time but then I eventually don't. And I'm doing this right now. How do I stop procrastinating?? Maybe just about all of those. :p Any tips on high school? It's because I'm going to start 9th grade 7 months from now, and I know high school is going to be worse than middle school. If only Ned made a high school guide "]
raw_post_count: 10
raw_char_count: 2785

In [37]:
data=pd.read_csv(source)

NameError: name 'source' is not defined

In [ ]:
data.shape

(321989, 5)

In [ ]:
data.columns

Index(['text', 'EI', 'NS', 'FT', 'JP'], dtype='str')

In [ ]:
data.head()

                                                text EI NS FT JP
0  What has been the most life-changing experienc...  I  N  F  J
1                        On repeat for most of today  I  N  F  J
2                May the PerC Experience immerse you  I  N  F  J
3  Prozac, wellbrutin, at least thirty minutes of...  I  N  F  J
4  All things in moderation. Sims is indeed a vid...  I  N  F  J

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df=data.copy()

In [ ]:
drop_cols =['EI','NS','FT','JP']# target data
df.drop(drop_cols, axis=1, inplace=True)

In [ ]:
df

                                                     text
0       What has been the most life-changing experienc...
1                             On repeat for most of today
2                     May the PerC Experience immerse you
3       Prozac, wellbrutin, at least thirty minutes of...
4       All things in moderation. Sims is indeed a vid...
...                                                   ...
321984                    those that you remember forever
321985  don't cry cause it's over , smile cause it hap...
321986             kutztown yesterday and montclair today
321987  screw college 9 weeks left minus weekends , pr...
321988  gorging on erin's bro's brownie lab so every g...

[321989 rows x 1 columns]